version: '3'
services:
  zookeeper:
    image: 'arm32v7/zookeeper:3.7.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    restart: always
  kafka:
    build:
      context: ./kafka
      dockerfile: Dockerfile.kafka
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: always
  spark:
    build:
      context: ./spark
      dockerfile: Dockerfile.spark
    container_name: spark
    ports:
      - '4040:4040'
    depends_on:
      - kafka
    environment:
      - SPARK_MASTER=local[*]
      - SPARK_SUBMIT_OPTS=-Djava.net.preferIPv4Stack=true
    restart: always
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile.airflow
    container_name: airflow
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
